sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t jin/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true jin/docker-react-app npm run test -- --coverage

# after_success:
#   - echo "Test suceess"

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-837396999574"
  bucket_path: "docker-react-app"
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SERET_ACCESS_KEY