sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t jin/docker-react-app -f Dckerfile.dev .

script:
  - docker run -e CI=true jin/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test suceess"

  